version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ujjwal
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskmanager
  backend:
    build: ./backend
    image: backend
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    links:
      - postgres
  frontend:
    build: ./client
    image: client
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    links:
      - backend